---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install webserver on ubuntu node
    apt:
      name: apache2
      state: present

  - name: i want to restart webserver on ubuntu node
    service: 
      name: apache2
      state: restarted